# Generated by Django 3.1.5 on 2021-01-13 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_post', '0001_initial'),
        ('anime_notification', '0002_auto_20210112_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follow_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='anime_post.animepost'),
        ),
    ]
