# Generated by Django 3.1.5 on 2021-01-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_user', '0002_auto_20210105_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
