# Generated by Django 3.1.5 on 2021-01-06 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_user', '0003_auto_20210106_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeuser',
            name='followers',
            field=models.ManyToManyField(blank=True, default='self', to=settings.AUTH_USER_MODEL),
        ),
    ]
