# Generated by Django 3.1.5 on 2021-01-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_user', '0005_auto_20210108_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
