# Generated by Django 3.1.5 on 2021-01-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.helper_file
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=helpers.helper_file.folder_path)),
                ('image_caption', models.TextField(max_length=600)),
                ('post_creation', models.DateField(auto_now_add=True)),
                ('anime_genre', models.CharField(choices=[('PICK_GENRE', 'CHOOSE GENRE'), ('SHONEN', 'SHONEN'), ('SHOUJU', 'SHOUJU'), ('SEINEN', 'SEINEN'), ('HAREM', 'HAREM'), ('ISEKAI', 'ISEKAI'), ('MECHA', 'MECHA'), ('SLICE_OF_LIFE', 'SLICE OF LIFE')], default='CHOOSE GENRE', max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('anime_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
