# Generated by Django 3.1.5 on 2021-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animepost',
            name='post_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date_post',
            field=models.DateField(auto_now_add=True),
        ),
    ]
