# Generated by Django 3.1.5 on 2021-01-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user',
            new_name='anime_user',
        ),
    ]
