# Generated by Django 3.1.5 on 2021-01-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_post', '0004_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='anime_post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='anime_user',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
