# Generated by Django 3.1.5 on 2021-01-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_post', '0005_auto_20210112_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='animepost',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
