# Generated by Django 3.1.5 on 2021-01-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='anime_post',
        ),
    ]
